Add checker to ensure that the servletContext is just loaded once. #17
resteasy/resteasy-grpc pull request #18
Opened 2023-08-10 15:55 UTC by liweinan

2023-08-10 16:06 UTC, jamezp requested changes

2023-08-10 17:48 UTC, liweinan commented on grpc-bridge/src/main/java/dev/resteasy/grpc/bridge/generator/ServerGrpcGenerator.java
> +                    .writeLine("private AtomicBoolean servletContextInitialized = new AtomicBoolean(false);");
yes sir!

2023-08-10 18:44 UTC, liweinan commented
The change is verified locally:

```bash
weli@192:~/w/g/w/bin
➤ curl http://localhost:8080/grpcToRest.example.grpc-1.0.1.Final-SNAPSHOT/grpcToJakartaRest/grpcserver/context        02:39:08

2Got org.greet.Greet_Server@414d9adc servletContext⏎
weli@192:~/w/g/w/bin
➤ curl http://localhost:8080/grpcToRest.example.grpc-1.0.1.Final-SNAPSHOT/grpcToJakartaRest/grpcserver/context        02:39:14

Borg.greet.Greet_Server@8c9ffbd servletContext already initialized.⏎
```

2023-08-15 01:32 UTC, jamezp approved these changes

2023-08-15 04:15 UTC, merged